export const DROPBOX_APP_KEY = import.meta.env.VITE_DROPBOX_APP_KEY;
export const GOODREADS_FETCHER_URL = import.meta.env.VITE_GOODREADS_FETCHER_URL;
export const GOODREADS_FETCHER_API_KEY = import.meta.env.VITE_GOODREADS_FETCHER_API_KEY;
